catalyst-auto: pass current targets down to post_build
Commit b7e493b4e4ad6cf6f9367e4b139df042526c21de (run trigger_post_build
after every successful spec) broke a lot of builders.  The configs were
written to be called only after everything was done, but by calling it
after the first build (stage1 only), all the other artifacts we expected
did not yet exist.

Change post_build to pass the current set & spec name down so the config
can figure out what is available at that point in time.

diff --git a/tools/catalyst-auto b/tools/catalyst-auto
--- a/tools/catalyst-auto
+++ b/tools/catalyst-auto
@@ -111,10 +111,11 @@ catalyst_var() {
 }
 
 trigger_post_build() {
-  if ! run_cmd "${TMPDIR}/log/post_build.log" post_build; then
-    send_email "Catalyst build error - post_build" "The post_build function failed" "${TMPDIR}/log/post_build.log"
-    exit 1
-  fi
+	local set=$1 spec=$2
+	if ! run_cmd "${TMPDIR}/log/post_build.log" post_build "${set}" "${spec}"; then
+		send_email "Catalyst build error - post_build" "The post_build function failed" "${TMPDIR}/log/post_build.log"
+		exit 1
+	fi
 }
 
 parse_args() {
@@ -365,7 +366,7 @@ run_catalyst_commands() {
 				send_email "Catalyst fatal build error - ${i}" "" "${LOGFILE}"
 				continue 2
 			else
-				trigger_post_build
+				trigger_post_build "${a}" "${i}"
 			fi
 		done
 
@@ -377,7 +378,7 @@ run_catalyst_commands() {
 				send_email "Catalyst non-fatal build error - ${i}" "" "${LOGFILE}"
 				break
 			else
-				trigger_post_build
+				trigger_post_build "${a}" "${i}"
 			fi
 		done
 
